{
 "title": "StatusPages",
 "tags": [
  "status",
  "exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Open Incidents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(statuspage_open_incidents) by (page)",
     "legendFormat": "{{page}}"
    }
   ]
  },
  {
   "title": "Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(statuspage_page_info) by (page,url)"
    }
   ]
  },
  {
   "title": "Scrape Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(statuspage_scrape_success) by (page)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(statuspage_component_status_code) by (page, group, component, status, region)"
    }
   ]
  }
 ]
}